### ISSUE TITLE
How to run test.py correctly?

### ISSUE THREAD

**Issue by ghost** [Maximellerbach/NumberRecognition#1]
Hello,Maxime Ellerbach
I get AI.h5 by train.py ,but when i run test.py,i meet some trouble.

I input your picture :NumberRecognition/input_image/P_20181222_143500.jpg
 when i np.reshape it.  It can't done, I don't know why it doesn't work? 
so i also can't use AI.h5 model to predicted this picture 

How can i get picture like NumberRecognition/input_image/P_20181222_143500_.png.
any help? Thanks

**Comment by Maximellerbach** [comment]
Hi, sorry for the long wait..

What is the error you get ?
